version: '3'

services:
  minidlna:
    build:
      context: .
    image: pauloromeira/minidlna:local
    container_name: minidlna
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./media/Videos:/media/Videos
      - ./media/Music:/media/Music
      - ./media/Pictures:/media/Pictures
