version: '3'

services:
  minidlna:
    build:
      context: .
    image: pauloromeira/minidlna:local
    container_name: minidlna
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./media/Music:/opt/minidlna/media/Music
      - ./media/Pictures:/opt/minidlna/media/Pictures
      - ./media/Videos:/opt/minidlna/media/Videos
