---
version: '3'

services:
  minidlna:
    build:
      context: .
    image: pauloromeira/minidlna:local
    container_name: minidlna
    network_mode: host
    restart: unless-stopped
    volumes:
      - "${MUSIC_DIR-./media/Music}:/srv/media/Music"
      - "${PICTURES_DIR-./media/Pictures}:/srv/media/Pictures"
      - "${VIDEOS_DIR-./media/Videos}:/srv/media/Videos"
